### ISSUE TITLE
Resource punkt not found.

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-classifiers#32]
```
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 2024-01-03 20:48:24.482 - skill-ovos-wikipedia.openvoiceos - ERROR - 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia **********************************************************************
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Resource punkt not found.
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Please use the NLTK Downloader to obtain the resource:
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   >>> import nltk
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   >>> nltk.download('punkt')
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   For more information see: https://www.nltk.org/data.html
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Attempted to load tokenizers/punkt/PY3/english.pickle
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Searched in:
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/.venv/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/.venv/share/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/.venv/lib/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/share/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/local/share/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/lib/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/local/lib/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - ''
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia **********************************************************************
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 2024-01-03 20:48:24.492 - OVOS - ovos_workshop.skills.common_query_skill:__get_cq:160 - ERROR - error matching explain me Quantum computing with skill-ovos-wikipedia.openvoiceos
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia Traceback (most recent call last):
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/common_query_skill.py", line 158, in __get_cq
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     result = self.CQS_match_query_phrase(search_phrase)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 201, in CQS_match_query_phrase
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     title, summary = self.ask_the_wiki(phrase)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                      ^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 227, in ask_the_wiki
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     self.image = self.wiki.get_image(query)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 100, in get_image
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     data = self.extract_and_search(query, context)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 55, in extract_and_search
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     query = self.extract_keyword(query, lang)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 39, in extract_keyword
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     return keyword_extractor.extract_subject(query, lang)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_classifiers/heuristics/keyword_extraction.py", line 58, in extract_subject
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     tagged_tokens = NltkPostag().tag(query)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                     ^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_classifiers/heuristics/postag.py", line 149, in tag
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     sentence = nltk.word_tokenize(sentence)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     sentences = [text] if preserve_line else sent_tokenize(text, language)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     tokenizer = load(f"tokenizers/punkt/{language}.pickle")
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/nltk/data.py", line 750, in load
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     opened_resource = _open(resource_url)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia                       ^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/nltk/data.py", line 876, in _open
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     return find(path_, path + [""]).open()
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia            ^^^^^^^^^^^^^^^^^^^^^^^^
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   File "/home/ovos/.venv/lib/python3.11/site-packages/nltk/data.py", line 583, in find
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     raise LookupError(resource_not_found)
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia LookupError: 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia **********************************************************************
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Resource punkt not found.
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Please use the NLTK Downloader to obtain the resource:
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   >>> import nltk
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   >>> nltk.download('punkt')
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   For more information see: https://www.nltk.org/data.html
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Attempted to load tokenizers/punkt/PY3/english.pickle
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia   Searched in:
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/.venv/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/.venv/share/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/home/ovos/.venv/lib/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/share/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/local/share/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/lib/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - '/usr/local/lib/nltk_data'
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia     - ''
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia **********************************************************************
ovos-skills-7f546bd6ff-h4kp9 ovos-skill-wikipedia 
```

**Comment by JarbasAl** [comment]
this is an issue for ovos-classifiers because of this https://github.com/OpenVoiceOS/skill-ovos-wikipedia/blob/dev/__init__.py#L38

**Comment by goldyfruit** [comment]
> this is an issue for ovos-classifiers because of this https://github.com/OpenVoiceOS/skill-ovos-wikipedia/blob/dev/__init__.py#L38

These are the missing downloads:

```python
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('universal_tagset')
```

**Comment by goldyfruit** [comment]
Thanks
